name: CI Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d 
  - name: Lint and Style
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run lint
  - name: Test
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run test
