name: CI Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_SECRET: some_complicated_secret
      STORAGE_DIR: /tmp/fakemoney_storage
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: "python -m pip install pipenv"
    - run: "pipenv install -d"
      name: "Installing project"
    - name: "Show pipenv scripts"
      run: "pipenv scripts"
    - run: "pipenv run lint"
      name: "Running Format Check"
    - run: "pipenv run test"
      name: "Running Tests"
